# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transaction.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(527, 205)
        self.horizontalLayout = QtWidgets.QHBoxLayout(dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.sender_nums = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sender_nums.sizePolicy().hasHeightForWidth())
        self.sender_nums.setSizePolicy(sizePolicy)
        self.sender_nums.setObjectName("sender_nums")
        self.horizontalLayout_2.addWidget(self.sender_nums)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.receivers_nums = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receivers_nums.sizePolicy().hasHeightForWidth())
        self.receivers_nums.setSizePolicy(sizePolicy)
        self.receivers_nums.setObjectName("receivers_nums")
        self.horizontalLayout_3.addWidget(self.receivers_nums)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.add_exception = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_exception.sizePolicy().hasHeightForWidth())
        self.add_exception.setSizePolicy(sizePolicy)
        self.add_exception.setObjectName("add_exception")
        self.horizontalLayout_4.addWidget(self.add_exception)
        self.transfer_num = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transfer_num.sizePolicy().hasHeightForWidth())
        self.transfer_num.setSizePolicy(sizePolicy)
        self.transfer_num.setObjectName("transfer_num")
        self.horizontalLayout_4.addWidget(self.transfer_num)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.begin_transfer = QtWidgets.QPushButton(self.frame)
        self.begin_transfer.setObjectName("begin_transfer")
        self.verticalLayout.addWidget(self.begin_transfer)
        self.horizontalLayout.addWidget(self.frame)
        self.stu_table = QtWidgets.QTableWidget(dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stu_table.sizePolicy().hasHeightForWidth())
        self.stu_table.setSizePolicy(sizePolicy)
        self.stu_table.setFrameShape(QtWidgets.QFrame.Box)
        self.stu_table.setObjectName("stu_table")
        self.stu_table.setColumnCount(0)
        self.stu_table.setRowCount(0)
        self.horizontalLayout.addWidget(self.stu_table)

        self.retranslateUi(dialog)
        self.begin_transfer.clicked.connect(dialog.begin_transaction)
        self.add_exception.clicked.connect(dialog.change_checkbox)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "事务管理"))
        self.label.setText(_translate("dialog", "转账学号："))
        self.label_2.setText(_translate("dialog", "收账学号："))
        self.add_exception.setText(_translate("dialog", "模拟异常：关"))
        self.begin_transfer.setText(_translate("dialog", "开始转帐"))
