# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 519)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 793, 184))
        self.widget.setObjectName("widget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.stu_num = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stu_num.sizePolicy().hasHeightForWidth())
        self.stu_num.setSizePolicy(sizePolicy)
        self.stu_num.setObjectName("stu_num")
        self.horizontalLayout.addWidget(self.stu_num)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.stu_name = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stu_name.sizePolicy().hasHeightForWidth())
        self.stu_name.setSizePolicy(sizePolicy)
        self.stu_name.setObjectName("stu_name")
        self.horizontalLayout_2.addWidget(self.stu_name)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.class_num = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.class_num.sizePolicy().hasHeightForWidth())
        self.class_num.setSizePolicy(sizePolicy)
        self.class_num.setObjectName("class_num")
        self.horizontalLayout_12.addWidget(self.class_num)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stu_insert = QtWidgets.QPushButton(self.frame)
        self.stu_insert.setObjectName("stu_insert")
        self.horizontalLayout_4.addWidget(self.stu_insert)
        self.stu_delete = QtWidgets.QPushButton(self.frame)
        self.stu_delete.setObjectName("stu_delete")
        self.horizontalLayout_4.addWidget(self.stu_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.course_num = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_num.sizePolicy().hasHeightForWidth())
        self.course_num.setSizePolicy(sizePolicy)
        self.course_num.setObjectName("course_num")
        self.horizontalLayout_6.addWidget(self.course_num)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.course_name = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_name.sizePolicy().hasHeightForWidth())
        self.course_name.setSizePolicy(sizePolicy)
        self.course_name.setObjectName("course_name")
        self.horizontalLayout_7.addWidget(self.course_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.teacher_num = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teacher_num.sizePolicy().hasHeightForWidth())
        self.teacher_num.setSizePolicy(sizePolicy)
        self.teacher_num.setObjectName("teacher_num")
        self.horizontalLayout_13.addWidget(self.teacher_num)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.course_insert = QtWidgets.QPushButton(self.frame_2)
        self.course_insert.setObjectName("course_insert")
        self.horizontalLayout_3.addWidget(self.course_insert)
        self.course_delete = QtWidgets.QPushButton(self.frame_2)
        self.course_delete.setObjectName("course_delete")
        self.horizontalLayout_3.addWidget(self.course_delete)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_10.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.line_3 = QtWidgets.QFrame(self.frame_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.sc_snum = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sc_snum.sizePolicy().hasHeightForWidth())
        self.sc_snum.setSizePolicy(sizePolicy)
        self.sc_snum.setObjectName("sc_snum")
        self.horizontalLayout_8.addWidget(self.sc_snum)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.sc_cnum = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sc_cnum.sizePolicy().hasHeightForWidth())
        self.sc_cnum.setSizePolicy(sizePolicy)
        self.sc_cnum.setObjectName("sc_cnum")
        self.horizontalLayout_9.addWidget(self.sc_cnum)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.sc_grade = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sc_grade.sizePolicy().hasHeightForWidth())
        self.sc_grade.setSizePolicy(sizePolicy)
        self.sc_grade.setObjectName("sc_grade")
        self.horizontalLayout_11.addWidget(self.sc_grade)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sc_insert = QtWidgets.QPushButton(self.frame_3)
        self.sc_insert.setObjectName("sc_insert")
        self.horizontalLayout_5.addWidget(self.sc_insert)
        self.sc_delete = QtWidgets.QPushButton(self.frame_3)
        self.sc_delete.setObjectName("sc_delete")
        self.horizontalLayout_5.addWidget(self.sc_delete)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10.addWidget(self.frame_3)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(0, 180, 778, 135))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_4 = QtWidgets.QFrame(self.widget1)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.line_4 = QtWidgets.QFrame(self.frame_4)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.sc_stu_count = QtWidgets.QSpinBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sc_stu_count.sizePolicy().hasHeightForWidth())
        self.sc_stu_count.setSizePolicy(sizePolicy)
        self.sc_stu_count.setObjectName("sc_stu_count")
        self.horizontalLayout_14.addWidget(self.sc_stu_count)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.name_query = QtWidgets.QPushButton(self.frame_4)
        self.name_query.setObjectName("name_query")
        self.verticalLayout_4.addWidget(self.name_query)
        self.horizontalLayout_17.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.widget1)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_15 = QtWidgets.QLabel(self.frame_5)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.line_5 = QtWidgets.QFrame(self.frame_5)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_5.addWidget(self.line_5)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        self.sc_stu_cnum = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sc_stu_cnum.sizePolicy().hasHeightForWidth())
        self.sc_stu_cnum.setSizePolicy(sizePolicy)
        self.sc_stu_cnum.setObjectName("sc_stu_cnum")
        self.horizontalLayout_16.addWidget(self.sc_stu_cnum)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.name_query_by_cnum = QtWidgets.QPushButton(self.frame_5)
        self.name_query_by_cnum.setObjectName("name_query_by_cnum")
        self.verticalLayout_5.addWidget(self.name_query_by_cnum)
        self.horizontalLayout_17.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.widget1)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_18 = QtWidgets.QLabel(self.frame_6)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_6.addWidget(self.label_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_17 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_19.addWidget(self.label_17)
        self.sc_stu_sname = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sc_stu_sname.sizePolicy().hasHeightForWidth())
        self.sc_stu_sname.setSizePolicy(sizePolicy)
        self.sc_stu_sname.setObjectName("sc_stu_sname")
        self.horizontalLayout_19.addWidget(self.sc_stu_sname)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.get_avg_grade = QtWidgets.QPushButton(self.frame_6)
        self.get_avg_grade.setObjectName("get_avg_grade")
        self.verticalLayout_6.addWidget(self.get_avg_grade)
        self.horizontalLayout_17.addWidget(self.frame_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action1_2 = QtWidgets.QAction(MainWindow)
        self.action1_2.setObjectName("action1_2")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.stu_insert_act = QtWidgets.QAction(MainWindow)
        self.stu_insert_act.setObjectName("stu_insert_act")
        self.stu_delete_act = QtWidgets.QAction(MainWindow)
        self.stu_delete_act.setObjectName("stu_delete_act")
        self.action1_4 = QtWidgets.QAction(MainWindow)
        self.action1_4.setObjectName("action1_4")
        self.action2_3 = QtWidgets.QAction(MainWindow)
        self.action2_3.setObjectName("action2_3")
        self.action3_2 = QtWidgets.QAction(MainWindow)
        self.action3_2.setObjectName("action3_2")
        self.action1_5 = QtWidgets.QAction(MainWindow)
        self.action1_5.setObjectName("action1_5")
        self.action2_4 = QtWidgets.QAction(MainWindow)
        self.action2_4.setObjectName("action2_4")
        self.stu_ = QtWidgets.QAction(MainWindow)
        self.stu_.setObjectName("stu_")

        self.retranslateUi(MainWindow)
        self.stu_delete.clicked.connect(MainWindow.stu_delete)
        self.stu_insert.clicked.connect(MainWindow.stu_insert)
        self.sc_insert.clicked.connect(MainWindow.sc_insert)
        self.sc_delete.clicked.connect(MainWindow.sc_delete)
        self.course_insert.clicked.connect(MainWindow.course_insert)
        self.course_delete.clicked.connect(MainWindow.course_delete)
        self.name_query.clicked.connect(MainWindow.get_name)
        self.name_query_by_cnum.clicked.connect(MainWindow.get_name_by_cnum)
        self.get_avg_grade.clicked.connect(MainWindow.get_avg_grade)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.stu_num, self.stu_name)
        MainWindow.setTabOrder(self.stu_name, self.stu_insert)
        MainWindow.setTabOrder(self.stu_insert, self.stu_delete)
        MainWindow.setTabOrder(self.stu_delete, self.course_num)
        MainWindow.setTabOrder(self.course_num, self.course_name)
        MainWindow.setTabOrder(self.course_name, self.teacher_num)
        MainWindow.setTabOrder(self.teacher_num, self.course_insert)
        MainWindow.setTabOrder(self.course_insert, self.course_delete)
        MainWindow.setTabOrder(self.course_delete, self.sc_snum)
        MainWindow.setTabOrder(self.sc_snum, self.sc_cnum)
        MainWindow.setTabOrder(self.sc_cnum, self.sc_grade)
        MainWindow.setTabOrder(self.sc_grade, self.sc_insert)
        MainWindow.setTabOrder(self.sc_insert, self.sc_delete)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "教学管理系统@zjr"))
        self.label.setText(_translate("MainWindow", "插入与删除：学生表操作"))
        self.label_2.setText(_translate("MainWindow", "学号："))
        self.label_3.setText(_translate("MainWindow", "姓名："))
        self.label_11.setText(_translate("MainWindow", "班号："))
        self.stu_insert.setText(_translate("MainWindow", "插入"))
        self.stu_delete.setText(_translate("MainWindow", "删除"))
        self.label_4.setText(_translate("MainWindow", "插入与删除：课程表操作"))
        self.label_5.setText(_translate("MainWindow", "课程号："))
        self.label_6.setText(_translate("MainWindow", "课程名："))
        self.label_12.setText(_translate("MainWindow", "教师号："))
        self.course_insert.setText(_translate("MainWindow", "插入"))
        self.course_delete.setText(_translate("MainWindow", "删除"))
        self.label_9.setText(_translate("MainWindow", "插入与删除：选课表操作"))
        self.label_7.setText(_translate("MainWindow", "学号："))
        self.label_8.setText(_translate("MainWindow", "课程号："))
        self.label_10.setText(_translate("MainWindow", "成绩："))
        self.sc_insert.setText(_translate("MainWindow", "插入"))
        self.sc_delete.setText(_translate("MainWindow", "删除"))
        self.label_13.setText(_translate("MainWindow", "查询超过一定选课数目的学生名：\n"
"选课表、学生表"))
        self.label_14.setText(_translate("MainWindow", "数目："))
        self.name_query.setText(_translate("MainWindow", "查询"))
        self.label_15.setText(_translate("MainWindow", "查询选修了该课程号的学生姓名：\n"
"选课表、学生表"))
        self.label_16.setText(_translate("MainWindow", "课程号："))
        self.name_query_by_cnum.setText(_translate("MainWindow", "查询"))
        self.label_18.setText(_translate("MainWindow", "查询该同学及格科目的平均成绩：\n"
"选课表、学生表"))
        self.label_17.setText(_translate("MainWindow", "姓名："))
        self.get_avg_grade.setText(_translate("MainWindow", "查询"))
        self.action1.setText(_translate("MainWindow", "待开发"))
        self.action1_2.setText(_translate("MainWindow", "1"))
        self.action2.setText(_translate("MainWindow", "2"))
        self.action3.setText(_translate("MainWindow", "3"))
        self.stu_insert_act.setText(_translate("MainWindow", "插入"))
        self.stu_delete_act.setText(_translate("MainWindow", "删除"))
        self.action1_4.setText(_translate("MainWindow", "1"))
        self.action2_3.setText(_translate("MainWindow", "2"))
        self.action3_2.setText(_translate("MainWindow", "3"))
        self.action1_5.setText(_translate("MainWindow", "1"))
        self.action2_4.setText(_translate("MainWindow", "2"))
        self.stu_.setText(_translate("MainWindow", "3"))
